project_id           = "dot-boom"                   
bucket_name          = "my-bucket-48693"
machine_type         = "e2-micro"
linux_image          = "ubuntu-os-pro-cloud/ubuntu-pro-1604-lts"
gce_ssh_user         = "andres"
gce_ssh_pub_key_file = "~/.ssh/kubernetes-lab-ssh-key.pub"
gce_ssh_key_file     = "~/.ssh/kubernetes-lab-ssh-key"
