project_id           = "dot-boom"                   
bucket_name          = "dot-boom-bucket"
machine_type         = "e2-micro"
linux_image          = "ubuntu-os-cloud/ubuntu-2004-lts"
gce_ssh_user         = "andres"
gce_ssh_pub_key_file = "~/.ssh/kubernetes-lab-ssh-key.pub"
gce_ssh_key_file     = "~/.ssh/kubernetes-lab-ssh-key"
