project_id           = "your_project_id" 
bucket_name          = "your_bucket_name"
machine_type         = "e2-micro"
linux_image          = "ubuntu-os-cloud/ubuntu-2004-lts"
gce_ssh_user         = "your_ssh_user"
gce_ssh_pub_key_file = "~/.ssh/kubernetes-lab-ssh-key.pub"
gce_ssh_key_file     = "~/.ssh/kubernetes-lab-ssh-key"
