- name: Add package source for Docker package
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

- name: Add source key for Docker repository
  ansible.builtin.apt_key:
    url:  https://download.docker.com/linux/ubuntu/gpg

- name: Update repositories database
  become: true
  apt:
    update_cache: yes

