---
- name: Jenkins provisioning
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Configure packages
      ansible.builtin.shell: dpkg --configure -a

    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: yes
    
    - name: Provide inventory file
      become: false
      ansible.builtin.shell: "bash node-list.sh"
        
- name: Provide Initial Setup to Master Node
  hosts: all
  become: true
  tasks:
    - name: Configure packages
      ansible.builtin.shell: dpkg --configure -a

    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install Ansible
      ansible.builtin.apt:
        name: "ansible"
        state: latest
    
    - name: Transfer SSH private key
      ansible.builtin.copy:
        src: "{{ lookup('ansible.builtin.env', 'SSH_KEY_PATH') }}"
        dest: "/home/{{ ansible_user }}/.ssh/"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'
    
    - name: Transfer inventory file
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/inventory.ini"
        dest: "/home/{{ ansible_user }}/"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
    
    - name: Transfer Main playbook
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/playbook.yml"
        dest: "/home/{{ ansible_user }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
    
    - name: Transfer Extra-mandatory playbook
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/harden-new-system.yml"
        dest: "/home/{{ ansible_user }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

- name: Ansible provisioning to Kubernetes Cluster
  hosts: all
  become: true
  tasks:
    - name: Execute Extra-mandatory Ansible playbook
      ansible.builtin.shell: ansible-playbook -i inventory.ini --private-key ~/.ssh/kubernetes-lab-ssh-key --ssh-extra-args '-o 'StrictHostKeyChecking no'' -u andres "{{ playbook_dir }}/harden-new-system.yml"
   
    - name: Execute Main Ansible playbook
      ansible.builtin.shell: ansible-playbook -i inventory.ini --private-key ~/.ssh/kubernetes-lab-ssh-key --ssh-extra-args '-o 'StrictHostKeyChecking no'' -u andres "{{ playbook_dir }}/playbook.yml"
